<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

namespace AQUILA_THEME\Inc;

use AQUILA_THEME\Inc\Traits\Singleton;

class Site_Options
{

	use Singleton;

	private $site_options_options;

	public function __construct()
	{
		// Loade class
		$this->setup_hooks();
	}
	protected function setup_hooks()
	{
		// Actions
		add_action('admin_menu', array($this, 'site_options_add_plugin_page'));
		add_action(
			'admin_init',
			array($this, 'site_options_page_init')
		);

		//  Filters

	}

	public function site_options_add_plugin_page()
	{
		add_menu_page(
			'Site Options', // page_title
			'Site Options', // menu_title
			'manage_options', // capability
			'site-options', // menu_slug
			array($this, 'site_options_create_admin_page'), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function site_options_create_admin_page()
	{
		$this->site_options_options = get_option('site_options_option_name'); ?>

		<div class="wrap">
			<h2>Site Options</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
				settings_fields('site_options_option_group');
				do_settings_sections('site-options-admin');
				submit_button();
				?>
			</form>
		</div>
<?php }

	public function site_options_page_init()
	{
		register_setting(
			'site_options_option_group', // option_group
			'site_options_option_name', // option_name
			array($this, 'site_options_sanitize') // sanitize_callback
		);

		add_settings_section(
			'site_options_setting_section', // id
			'Settings', // title
			array($this, 'site_options_section_info'), // callback
			'site-options-admin' // page
		);

		add_settings_field(
			'facebook_0', // id
			'Facebook', // title
			array($this, 'facebook_0_callback'), // callback
			'site-options-admin', // page
			'site_options_setting_section' // section
		);

		add_settings_field(
			'inastagram_1', // id
			'Inastagram', // title
			array($this, 'inastagram_1_callback'), // callback
			'site-options-admin', // page
			'site_options_setting_section' // section
		);
	}

	public function site_options_sanitize($input)
	{
		$sanitary_values = array();
		if (isset($input['facebook_0'])) {
			$sanitary_values['facebook_0'] = sanitize_text_field($input['facebook_0']);
		}

		if (isset($input['inastagram_1'])) {
			$sanitary_values['inastagram_1'] = sanitize_text_field($input['inastagram_1']);
		}

		return $sanitary_values;
	}

	public function site_options_section_info()
	{
	}

	public function facebook_0_callback()
	{
		printf(
			'<input class="regular-text" type="text" name="site_options_option_name[facebook_0]" id="facebook_0" value="%s">',
			isset($this->site_options_options['facebook_0']) ? esc_attr($this->site_options_options['facebook_0']) : ''
		);
	}

	public function inastagram_1_callback()
	{
		printf(
			'<input class="regular-text" type="text" name="site_options_option_name[inastagram_1]" id="inastagram_1" value="%s">',
			isset($this->site_options_options['inastagram_1']) ? esc_attr($this->site_options_options['inastagram_1']) : ''
		);
	}
}
// if (is_admin())
// 	$site_options = new SiteOptions();

/* 
 * Retrieve this value with:
 * $site_options_options = get_option( 'site_options_option_name' ); // Array of All Options
 * $facebook_0 = $site_options_options['facebook_0']; // Facebook
 * $inastagram_1 = $site_options_options['inastagram_1']; // Inastagram
 */
